config:
  url: http://127.0.0.1:9301/mes/algorithmFile/updateAlgorithmFileOutputPath
  outputPath: D://data//
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/planner?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: iamno.1
